name: Insert Documents Into Collection

on:
  push:
    branches: 
      - main

jobs:
  run_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Pytest 3.6
      uses: actions/setup-python@v2
      with:
        python-version: '3.6'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        python3 -m pip install vectorai
        python3 -m pip install torch torchvision
        python3 -m pip install transformers==3.5.1
        python3 -m pip install tensorflow-text
        python3 -m pip install sentencepiece
    - name: Creating models.json
      env:
            VH_USERNAME: ${{ secrets.VI_USERNAME }}
            VH_API_KEY: ${{ secrets.VI_API_KEY }}
            VH_COLLECTION_NAME: ${{secrets.VH_COLLECTION_NAME}}
        
      run: |
        python3 utils/upload_cards.py --reset_collection
